// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AOC2020_Day6$AdventOfCode = require("./AOC2020_Day6.bs.js");
var AOC2020_Day6_Data$AdventOfCode = require("./AOC2020_Day6_Data.bs.js");
var AOC2020_Day6_Data_Sample$AdventOfCode = require("./AOC2020_Day6_Data_Sample.bs.js");

function log(prim) {
  console.log(prim);
  
}

var part1 = AOC2020_Day6$AdventOfCode.solvePart1(AOC2020_Day6_Data$AdventOfCode.data);

console.log("Part 1 Result");

console.log(part1);

var part2 = AOC2020_Day6$AdventOfCode.solvePart2(AOC2020_Day6_Data$AdventOfCode.data);

console.log("Part 2 Result");

console.log(part2);

var data = AOC2020_Day6_Data$AdventOfCode.data;

var testData = AOC2020_Day6_Data_Sample$AdventOfCode.data;

exports.log = log;
exports.data = data;
exports.testData = testData;
exports.part1 = part1;
exports.part2 = part2;
/* part1 Not a pure module */
