// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var data = "abc\n\n            a\n            b\n            c\n\n            ab\n            ac\n\n            a\n            a\n            a\n            a\n\n            b";

exports.data = data;
/* No side effect */
