// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Utils$AdventOfCode = require("../../Utils.bs.js");

function log(prim) {
  console.log(prim);
  
}

function make(op, arg) {
  console.log([
        op,
        arg
      ]);
  return 1;
}

var Instruction = {
  make: make
};

function parseLine(l) {
  var x = l.trim().split(" ");
  var op = Belt_Array.get(x, 0);
  var arg = Belt_Array.get(x, 1);
  return make(op, arg);
}

function parse(data) {
  return Belt_Array.map(Utils$AdventOfCode.splitNewline(data), parseLine);
}

function solvePart1(data) {
  return Belt_Array.map(Utils$AdventOfCode.splitNewline(data), parseLine);
}

function solvePart2(data) {
  return 2;
}

exports.log = log;
exports.Instruction = Instruction;
exports.parseLine = parseLine;
exports.parse = parse;
exports.solvePart1 = solvePart1;
exports.solvePart2 = solvePart2;
/* No side effect */
