// Generated by ReScript, PLEASE EDIT WITH CARE


let data = "nop +0\n            acc +1\n            jmp +4\n            acc +3\n            jmp -3\n            acc -99\n            acc +1\n            jmp -4\n            acc +6";

export {
  data,
}
/* No side effect */
