// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AOC2020_Day8$AdventOfCode = require("./AOC2020_Day8.bs.js");
var AOC2020_Day8_Data$AdventOfCode = require("./AOC2020_Day8_Data.bs.js");
var AOC2020_Day8_Data_Sample$AdventOfCode = require("./AOC2020_Day8_Data_Sample.bs.js");

function log(prim) {
  console.log(prim);
  
}

var part2 = AOC2020_Day8$AdventOfCode.solvePart2(AOC2020_Day8_Data$AdventOfCode.data);

console.log("Part 2 Result");

console.log(part2);

var data = AOC2020_Day8_Data$AdventOfCode.data;

var sampleData = AOC2020_Day8_Data_Sample$AdventOfCode.data;

exports.log = log;
exports.data = data;
exports.sampleData = sampleData;
exports.part2 = part2;
/* part2 Not a pure module */
