// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2025_Day1$AdventOfCode from "./AOC2025_Day1.res.mjs";
import * as AOC2025_Day1_Data$AdventOfCode from "./AOC2025_Day1_Data.res.mjs";
import * as AOC2025_Day1_Data_Sample$AdventOfCode from "./AOC2025_Day1_Data_Sample.res.mjs";

Jest.describe("2025 Day1", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2025_Day1$AdventOfCode.solvePart1(AOC2025_Day1_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2025_Day1$AdventOfCode.solvePart1(AOC2025_Day1_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 1084);
  });
  Jest.testAll("Part 2 - Test Data", {
    hd: [
      "L75",
      1
    ],
    tl: /* [] */0
  }, param => {
    let result = AOC2025_Day1$AdventOfCode.solvePart2(param[0]);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), param[1]);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2025_Day1$AdventOfCode.solvePart2(AOC2025_Day1_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 6);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2025_Day1$AdventOfCode.solvePart2(AOC2025_Day1_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 6475);
  });
});

let data = AOC2025_Day1_Data$AdventOfCode.data;

let sampleData = AOC2025_Day1_Data_Sample$AdventOfCode.data;

let solvePart1 = AOC2025_Day1$AdventOfCode.solvePart1;

let solvePart2 = AOC2025_Day1$AdventOfCode.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
