// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2020_Day1$AdventOfCode from "./AOC2020_Day1.mjs";
import * as AOC2020_Day1_Data$AdventOfCode from "./AOC2020_Day1_Data.mjs";
import * as AOC2020_Day1_Data_Sample$AdventOfCode from "./AOC2020_Day1_Data_Sample.mjs";

function log(prim) {
  console.log(prim);
  
}

var part1 = AOC2020_Day1$AdventOfCode.solvePart2(AOC2020_Day1_Data$AdventOfCode.data);

console.log(part1);

var data = AOC2020_Day1_Data$AdventOfCode.data;

var sampleData = AOC2020_Day1_Data_Sample$AdventOfCode.data;

export {
  log ,
  data ,
  sampleData ,
  part1 ,
  
}
/* part1 Not a pure module */
