// Generated by ReScript, PLEASE EDIT WITH CARE


let data = "vJrwpWtwJgWrhcsFMMfFFhFp\n            jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n            PmmdzqPrVvPwwTWBwg\n            wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n            ttgJtRGJQctTZtZT\n            CrZsJsPPZsGzwwsLwLmpwMDw";

export {
  data,
}
/* No side effect */
