// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AOC2018_Day6$AdventOfCode = require("./AOC2018_Day6.bs.js");
var AOC2018_Day6_Data$AdventOfCode = require("./AOC2018_Day6_Data.bs.js");
var AOC2018_Day6_Data_Test$AdventOfCode = require("./AOC2018_Day6_Data_Test.bs.js");

function log(prim) {
  console.log(prim);
  
}

var part1 = AOC2018_Day6$AdventOfCode.solvePart1(AOC2018_Day6_Data_Test$AdventOfCode.data);

console.log(part1);

var data = AOC2018_Day6_Data$AdventOfCode.data;

var testData = AOC2018_Day6_Data_Test$AdventOfCode.data;

exports.log = log;
exports.data = data;
exports.testData = testData;
exports.part1 = part1;
/* part1 Not a pure module */
