// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2024_Day9 from "./AOC2024_Day9.res.mjs";
import * as AOC2024_Day9_Data from "./AOC2024_Day9_Data.res.mjs";
import * as AOC2024_Day9_Data_Sample from "./AOC2024_Day9_Data_Sample.res.mjs";

function log(prim) {
  console.log(prim);
}

console.time("Part 1");

console.time("Part 2");

let part2 = AOC2024_Day9.solvePart2(AOC2024_Day9_Data_Sample.data);

console.log("Part 2 Result");

console.log(part2);

console.timeEnd("Part 2");

let data = AOC2024_Day9_Data.data;

let sampleData = AOC2024_Day9_Data_Sample.data;

let solvePart1 = AOC2024_Day9.solvePart1;

let solvePart2 = AOC2024_Day9.solvePart2;

export {
  log,
  data,
  sampleData,
  solvePart1,
  solvePart2,
  part2,
}
/*  Not a pure module */
