// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2020_Day2$AdventOfCode from "./AOC2020_Day2.mjs";
import * as AOC2020_Day2_Data$AdventOfCode from "./AOC2020_Day2_Data.mjs";
import * as AOC2020_Day2_Data_Sample$AdventOfCode from "./AOC2020_Day2_Data_Sample.mjs";

Jest.describe("2020 Day2", (function () {
        Jest.test("Part 1 - Test Data", (function () {
                var result = AOC2020_Day2$AdventOfCode.solvePart1(AOC2020_Day2_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 2);
              }));
        Jest.test("Part 1 - Solve", (function () {
                var result = AOC2020_Day2$AdventOfCode.solvePart1(AOC2020_Day2_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 383);
              }));
        Jest.test("Part 2 - Solve", (function () {
                var result = AOC2020_Day2$AdventOfCode.solvePart2(AOC2020_Day2_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 272);
              }));
      }));

var data = AOC2020_Day2_Data$AdventOfCode.data;

var sampleData = AOC2020_Day2_Data_Sample$AdventOfCode.data;

export {
  data ,
  sampleData ,
}
/*  Not a pure module */
