// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.bs.js";
import * as AOC2021_Day6$AdventOfCode from "./AOC2021_Day6.bs.js";
import * as AOC2021_Day6_Data$AdventOfCode from "./AOC2021_Day6_Data.bs.js";
import * as AOC2021_Day6_Data_Sample$AdventOfCode from "./AOC2021_Day6_Data_Sample.bs.js";

Jest.describe("2021 Day6", (function (param) {
        Jest.test("Part 1 - Sample Data", (function (param) {
                var result = AOC2021_Day6$AdventOfCode.solvePart1(AOC2021_Day6_Data_Sample$AdventOfCode.data);
                var expected = String(5934);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), expected);
              }));
        Jest.test("Part 1 - Solve", (function (param) {
                var result = AOC2021_Day6$AdventOfCode.solvePart1(AOC2021_Day6_Data$AdventOfCode.data);
                var expected = String(379414);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), expected);
              }));
        Jest.test("Part 2 - Sample Data", (function (param) {
                var result = AOC2021_Day6$AdventOfCode.solvePart2(AOC2021_Day6_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), "26984457539");
              }));
        return Jest.test("Part 2 - Solve", (function (param) {
                      var result = AOC2021_Day6$AdventOfCode.solvePart2(AOC2021_Day6_Data$AdventOfCode.data);
                      return Jest.Expect.toEqual(Jest.Expect.expect(result), "1705008653296");
                    }));
      }));

var data = AOC2021_Day6_Data$AdventOfCode.data;

var sampleData = AOC2021_Day6_Data_Sample$AdventOfCode.data;

export {
  data ,
  sampleData ,
  
}
/*  Not a pure module */
