// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils$AdventOfCode from "../../Utils.bs.js";
import * as AOC2018_Day5$AdventOfCode from "./AOC2018_Day5.bs.js";

var result = AOC2018_Day5$AdventOfCode.solvePart2(AOC2018_Day5$AdventOfCode.aTod, AOC2018_Day5$AdventOfCode.testCharArray);

Utils$AdventOfCode.log(result);

export {
  result ,
  
}
/* result Not a pure module */
