// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Day5$AdventOfCode = require("./Day5.bs.js");
var Utils$AdventOfCode = require("../Utils.bs.js");

var result = Day5$AdventOfCode.solvePart2(Day5$AdventOfCode.aTod, Day5$AdventOfCode.testCharArray);

Utils$AdventOfCode.log(result);

exports.result = result;
/* result Not a pure module */
