// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2021_Day12 from "./AOC2021_Day12.res.mjs";
import * as AOC2021_Day12_Data from "./AOC2021_Day12_Data.res.mjs";
import * as AOC2021_Day12_Data_Sample from "./AOC2021_Day12_Data_Sample.res.mjs";

Jest.describe("2021 Day12", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2021_Day12.solvePart1(AOC2021_Day12_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 226);
  });
  Jest.test("Part 1 - Sample Data 0", () => {
    let result = AOC2021_Day12.solvePart1(AOC2021_Day12_Data_Sample.data0);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 10);
  });
  Jest.test("Part 1 - Sample Data 1", () => {
    let result = AOC2021_Day12.solvePart1(AOC2021_Day12_Data_Sample.data1);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 19);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2021_Day12.solvePart1(AOC2021_Day12_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 4338);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2021_Day12.solvePart2(AOC2021_Day12_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3509);
  });
  Jest.test("Part 2 - Sample Data 0", () => {
    let result = AOC2021_Day12.solvePart2(AOC2021_Day12_Data_Sample.data0);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 36);
  });
  Jest.test("Part 2 - Sample Data 1", () => {
    let result = AOC2021_Day12.solvePart2(AOC2021_Day12_Data_Sample.data1);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 103);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2021_Day12.solvePart2(AOC2021_Day12_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 114189);
  });
});

let data = AOC2021_Day12_Data.data;

let sampleData = AOC2021_Day12_Data_Sample.data;

let sampleData0 = AOC2021_Day12_Data_Sample.data0;

let sampleData1 = AOC2021_Day12_Data_Sample.data1;

export {
  data,
  sampleData,
  sampleData0,
  sampleData1,
}
/*  Not a pure module */
