// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2022_Day10$AdventOfCode from "./AOC2022_Day10.mjs";
import * as AOC2022_Day10_Data$AdventOfCode from "./AOC2022_Day10_Data.mjs";
import * as AOC2022_Day10_Data_Sample$AdventOfCode from "./AOC2022_Day10_Data_Sample.mjs";

Jest.describe("2022 Day10", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2022_Day10$AdventOfCode.solvePart1(AOC2022_Day10_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 13140);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2022_Day10$AdventOfCode.solvePart1(AOC2022_Day10_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 14760);
  });
  Jest.test("Part 2 - Sample Data - Bogus - read the log output", () => {
    let result = AOC2022_Day10$AdventOfCode.solvePart2(AOC2022_Day10_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), "EFGERURE");
  });
  Jest.test("Part 2 - Solve - Bogus - read the log output", () => {
    let result = AOC2022_Day10$AdventOfCode.solvePart2(AOC2022_Day10_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), "EFGERURE");
  });
});

let data = AOC2022_Day10_Data$AdventOfCode.data;

let sampleData = AOC2022_Day10_Data_Sample$AdventOfCode.data;

let solvePart1 = AOC2022_Day10$AdventOfCode.solvePart1;

let solvePart2 = AOC2022_Day10$AdventOfCode.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
