// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2020_Day5$AdventOfCode from "./AOC2020_Day5.mjs";
import * as AOC2020_Day5_Data$AdventOfCode from "./AOC2020_Day5_Data.mjs";
import * as AOC2020_Day5_Data_Sample$AdventOfCode from "./AOC2020_Day5_Data_Sample.mjs";

Jest.describe("2020 Day5", (function (param) {
        Jest.test("Part 1 - Test Data", (function (param) {
                var result = AOC2020_Day5$AdventOfCode.solvePart1(AOC2020_Day5_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 820);
              }));
        Jest.test("Part 1 - Solve", (function (param) {
                var result = AOC2020_Day5$AdventOfCode.solvePart1(AOC2020_Day5_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 908);
              }));
        return Jest.test("Part 2 - Solve", (function (param) {
                      var result = AOC2020_Day5$AdventOfCode.solvePart2(AOC2020_Day5_Data$AdventOfCode.data);
                      return Jest.Expect.toEqual(Jest.Expect.expect(result), 619);
                    }));
      }));

var data = AOC2020_Day5_Data$AdventOfCode.data;

var sampleData = AOC2020_Day5_Data_Sample$AdventOfCode.data;

export {
  data ,
  sampleData ,
  
}
/*  Not a pure module */
