// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils$AdventOfCode from "../../Utils.mjs";
import * as Stdlib_Array$AdventOfCode from "../../stdlib/Stdlib_Array.mjs";
import * as Stdlib_Function$AdventOfCode from "../../stdlib/Stdlib_Function.mjs";

function log(prim) {
  console.log(prim);
}

var parse = Utils$AdventOfCode.splitChars;

function allDifferent(cs) {
  return Stdlib_Array$AdventOfCode.eq(Stdlib_Array$AdventOfCode.uniq(cs), cs, (function (prim0, prim1) {
                return prim0 === prim1;
              }));
}

function hasSame(x) {
  return !allDifferent(x);
}

function interestingPosition(n, text) {
  var len = text.length;
  var candidates = Stdlib_Array$AdventOfCode.zip(Stdlib_Array$AdventOfCode.makeBy(len, Stdlib_Function$AdventOfCode.identity), Stdlib_Array$AdventOfCode.map(Stdlib_Array$AdventOfCode.tails(text), (function (__x) {
              return Stdlib_Array$AdventOfCode.take(__x, n);
            })));
  var packetPos = Stdlib_Array$AdventOfCode.head(Stdlib_Array$AdventOfCode.dropWhile(candidates, (function (param) {
              return Utils$AdventOfCode.compose((function (prim) {
                            return prim[1];
                          }), hasSame, param);
            })));
  return n + packetPos[0] | 0;
}

function solvePart1(data) {
  return interestingPosition(4, Utils$AdventOfCode.splitChars(data));
}

function solvePart2(data) {
  return interestingPosition(14, Utils$AdventOfCode.splitChars(data));
}

var A;

export {
  log ,
  A ,
  parse ,
  allDifferent ,
  hasSame ,
  interestingPosition ,
  solvePart1 ,
  solvePart2 ,
}
/* No side effect */
