// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../Utils.res.mjs";
import * as Stdlib__Int from "@dsiu/rescript-stdlib-fp/src/Stdlib__Int.res.mjs";
import * as Stdlib__Array from "@dsiu/rescript-stdlib-fp/src/Stdlib__Array.res.mjs";

function log(prim) {
  console.log(prim);
}

function fuel(mass) {
  return (mass / 3 | 0) - 2 | 0;
}

function part1(xs) {
  return Stdlib__Array.sum(xs.map(fuel), {
    zero: Stdlib__Int.zero,
    add: Stdlib__Int.add
  });
}

function fuelCompound(mass) {
  let _mass = mass;
  let _acc = 0;
  while (true) {
    let acc = _acc;
    let mass$1 = _mass;
    let mass$p = fuel(mass$1);
    if (mass$p <= 0) {
      return acc;
    }
    _acc = acc + mass$p | 0;
    _mass = mass$p;
    continue;
  };
}

function part2(xs) {
  return Stdlib__Array.sum(xs.map(fuelCompound), {
    zero: Stdlib__Int.zero,
    add: Stdlib__Int.add
  });
}

function parse(data) {
  return Utils.splitNewline(data).map(Utils.intFromStringExn);
}

function solvePart1(data) {
  return part1(Utils.splitNewline(data).map(Utils.intFromStringExn));
}

function solvePart2(data) {
  return part2(Utils.splitNewline(data).map(Utils.intFromStringExn));
}

export {
  log,
  fuel,
  part1,
  fuelCompound,
  part2,
  parse,
  solvePart1,
  solvePart2,
}
/* Utils Not a pure module */
