// Generated by ReScript, PLEASE EDIT WITH CARE


let data = "forward 5\n            down 5\n            forward 8\n            up 3\n            down 8\n            forward 2";

export {
  data,
}
/* No side effect */
