// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2025_Day2$AdventOfCode from "./AOC2025_Day2.res.mjs";
import * as AOC2025_Day2_Data$AdventOfCode from "./AOC2025_Day2_Data.res.mjs";
import * as AOC2025_Day2_Data_Sample$AdventOfCode from "./AOC2025_Day2_Data_Sample.res.mjs";

Jest.describe("2025 Day2", () => {
  Jest.test("Part 1 - Sample Data", () => {
    AOC2025_Day2$AdventOfCode.solvePart1(AOC2025_Day2_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(true), true);
  });
  Jest.test("Part 1 - Solve", () => {
    (1n).toString();
    return Jest.Expect.toEqual(Jest.Expect.expect(true), true);
  });
  Jest.test("Part 2 - Sample Data", () => {
    AOC2025_Day2$AdventOfCode.solvePart2(AOC2025_Day2_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(true), true);
  });
  Jest.test("Part 2 - Solve", () => {
    AOC2025_Day2$AdventOfCode.solvePart2(AOC2025_Day2_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(true), true);
  });
});

let data = AOC2025_Day2_Data$AdventOfCode.data;

let sampleData = AOC2025_Day2_Data_Sample$AdventOfCode.data;

let solvePart1 = AOC2025_Day2$AdventOfCode.solvePart1;

let solvePart2 = AOC2025_Day2$AdventOfCode.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
