// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "--- scanner 0 ---\n            -1,-1,1\n            -2,-2,2\n            -3,-3,3\n            -2,-3,1\n            5,6,-4\n            8,0,7\n\n            --- scanner 129 ---\n            1,2,3";

export {
  data ,
  
}
/* No side effect */
