// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2021_Day19$AdventOfCode from "./AOC2021_Day19.mjs";
import * as AOC2021_Day19_Data$AdventOfCode from "./AOC2021_Day19_Data.mjs";
import * as AOC2021_Day19_Data_Sample$AdventOfCode from "./AOC2021_Day19_Data_Sample.mjs";

Jest.describe("2021 Day19", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2021_Day19$AdventOfCode.solvePart1(AOC2021_Day19_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 79);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2021_Day19$AdventOfCode.solvePart1(AOC2021_Day19_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 394);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2021_Day19$AdventOfCode.solvePart2(AOC2021_Day19_Data_Sample$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3621);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2021_Day19$AdventOfCode.solvePart2(AOC2021_Day19_Data$AdventOfCode.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 12304);
  });
});

let data = AOC2021_Day19_Data$AdventOfCode.data;

let sampleData = AOC2021_Day19_Data_Sample$AdventOfCode.data;

let solvePart1 = AOC2021_Day19$AdventOfCode.solvePart1;

let solvePart2 = AOC2021_Day19$AdventOfCode.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
