// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2024_Day3 from "./AOC2024_Day3.res.mjs";
import * as AOC2024_Day3_Data from "./AOC2024_Day3_Data.res.mjs";
import * as AOC2024_Day3_Data_Sample from "./AOC2024_Day3_Data_Sample.res.mjs";

Jest.describe("2024 Day3", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2024_Day3.solvePart1(AOC2024_Day3_Data_Sample.data1);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 161);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2024_Day3.solvePart1(AOC2024_Day3_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 182780583);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2024_Day3.solvePart2(AOC2024_Day3_Data_Sample.data2);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 48);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2024_Day3.solvePart2(AOC2024_Day3_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 90772405);
  });
});

let data = AOC2024_Day3_Data.data;

let sampleData1 = AOC2024_Day3_Data_Sample.data1;

let sampleData2 = AOC2024_Day3_Data_Sample.data2;

let solvePart1 = AOC2024_Day3.solvePart1;

let solvePart2 = AOC2024_Day3.solvePart2;

export {
  data,
  sampleData1,
  sampleData2,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
