// Generated by ReScript, PLEASE EDIT WITH CARE


let data = "L.LL.LL.LL\n            LLLLLLL.LL\n            L.L.L..L..\n            LLLL.LL.LL\n            L.LL.LL.LL\n            L.LLLLL.LL\n            ..L.L.....\n            LLLLLLLLLL\n            L.LLLLLL.L\n            L.LLLLL.LL";

export {
  data,
}
/* No side effect */
