// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "O....#....\n            O.OO#....#\n            .....##...\n            OO.#O....O\n            .O.....O#.\n            O.#..O.#.#\n            ..O..#O..O\n            .......O..\n            #....###..\n            #OO..#....";

export {
  data ,
}
/* No side effect */
