// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "6111821767\n            1763611615\n            3512683131\n            8582771473\n            8214813874\n            2325823217\n            2222482823\n            5471356782\n            3738671287\n            8675226574";

export {
  data ,
}
/* No side effect */
