// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2021_Day15 from "./AOC2021_Day15.res.mjs";
import * as AOC2021_Day15_Data from "./AOC2021_Day15_Data.res.mjs";
import * as AOC2021_Day15_Data_Sample from "./AOC2021_Day15_Data_Sample.res.mjs";

Jest.describe("2021 Day15", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2021_Day15.solvePart1(AOC2021_Day15_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 40);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2021_Day15.solvePart1(AOC2021_Day15_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 811);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2021_Day15.solvePart2(AOC2021_Day15_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 315);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2021_Day15.solvePart2(AOC2021_Day15_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3012);
  });
});

let data = AOC2021_Day15_Data.data;

let sampleData = AOC2021_Day15_Data_Sample.data;

let solvePart1 = AOC2021_Day15.solvePart1;

let solvePart2 = AOC2021_Day15.solvePart2;

let Cave;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
  Cave,
}
/*  Not a pure module */
