// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2021_Day15$AdventOfCode from "./AOC2021_Day15.mjs";
import * as AOC2021_Day15_Data$AdventOfCode from "./AOC2021_Day15_Data.mjs";
import * as AOC2021_Day15_Data_Sample$AdventOfCode from "./AOC2021_Day15_Data_Sample.mjs";

function log(prim) {
  console.log(prim);
  
}

var part1 = AOC2021_Day15$AdventOfCode.solvePart1(AOC2021_Day15_Data$AdventOfCode.data);

console.log("Part 1 Result");

console.log(part1);

var part2 = AOC2021_Day15$AdventOfCode.solvePart2(AOC2021_Day15_Data$AdventOfCode.data);

console.log("Part 2 Result");

console.log(part2);

var data = AOC2021_Day15_Data$AdventOfCode.data;

var sampleData = AOC2021_Day15_Data_Sample$AdventOfCode.data;

var sampleData2 = AOC2021_Day15_Data_Sample$AdventOfCode.data2;

var solvePart1 = AOC2021_Day15$AdventOfCode.solvePart1;

var solvePart2 = AOC2021_Day15$AdventOfCode.solvePart2;

export {
  log ,
  data ,
  sampleData ,
  sampleData2 ,
  solvePart1 ,
  solvePart2 ,
  part1 ,
  part2 ,
  
}
/* part1 Not a pure module */
