// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

function map_string_dump(m) {
  return Belt_MapString.forEach(m, (function (k, v) {
                console.log("key:" + k + ", val:" + String(v));
                
              }));
}

exports.map_string_dump = map_string_dump;
/* No side effect */
