// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2021_Day14 from "./AOC2021_Day14.res.mjs";
import * as AOC2021_Day14_Data from "./AOC2021_Day14_Data.res.mjs";
import * as AOC2021_Day14_Data_Sample from "./AOC2021_Day14_Data_Sample.res.mjs";

Jest.describe("2021 Day14", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2021_Day14.solvePart1(AOC2021_Day14_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 1588n);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2021_Day14.solvePart1(AOC2021_Day14_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3306n);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2021_Day14.solvePart2(AOC2021_Day14_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 2188189693529n);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2021_Day14.solvePart2(AOC2021_Day14_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 3760312702877n);
  });
});

let data = AOC2021_Day14_Data.data;

let sampleData = AOC2021_Day14_Data_Sample.data;

let solvePart1 = AOC2021_Day14.solvePart1;

let solvePart2 = AOC2021_Day14.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
