// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2021_Day14$AdventOfCode from "./AOC2021_Day14.mjs";
import * as AOC2021_Day14_Data$AdventOfCode from "./AOC2021_Day14_Data.mjs";
import * as AOC2021_Day14_Data_Sample$AdventOfCode from "./AOC2021_Day14_Data_Sample.mjs";

Jest.describe("2021 Day14", (function (param) {
        Jest.test("Part 1 - Sample Data", (function (param) {
                var result = AOC2021_Day14$AdventOfCode.solvePart1(AOC2021_Day14_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), [
                            0,
                            1588
                          ]);
              }));
        Jest.test("Part 1 - Solve", (function (param) {
                var result = AOC2021_Day14$AdventOfCode.solvePart1(AOC2021_Day14_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), [
                            0,
                            3306
                          ]);
              }));
        Jest.test("Part 2 - Sample Data", (function (param) {
                var result = AOC2021_Day14$AdventOfCode.solvePart2(AOC2021_Day14_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), [
                            509,
                            2051339865
                          ]);
              }));
        Jest.test("Part 2 - Solve", (function (param) {
                var result = AOC2021_Day14$AdventOfCode.solvePart2(AOC2021_Day14_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), [
                            875,
                            2216318877
                          ]);
              }));
      }));

var data = AOC2021_Day14_Data$AdventOfCode.data;

var sampleData = AOC2021_Day14_Data_Sample$AdventOfCode.data;

var solvePart1 = AOC2021_Day14$AdventOfCode.solvePart1;

var solvePart2 = AOC2021_Day14$AdventOfCode.solvePart2;

export {
  data ,
  sampleData ,
  solvePart1 ,
  solvePart2 ,
}
/*  Not a pure module */
