// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2023_Day2$AdventOfCode from "./AOC2023_Day2.mjs";
import * as AOC2023_Day2_Data$AdventOfCode from "./AOC2023_Day2_Data.mjs";
import * as AOC2023_Day2_Data_Sample$AdventOfCode from "./AOC2023_Day2_Data_Sample.mjs";

Jest.describe("2023 Day2", (function () {
        Jest.test("Part 1 - Sample Data", (function () {
                var result = AOC2023_Day2$AdventOfCode.solvePart1(AOC2023_Day2_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 8);
              }));
        Jest.test("Part 1 - Solve", (function () {
                var result = AOC2023_Day2$AdventOfCode.solvePart1(AOC2023_Day2_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 2679);
              }));
        Jest.test("Part 2 - Sample Data", (function () {
                var result = AOC2023_Day2$AdventOfCode.solvePart2(AOC2023_Day2_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 2286);
              }));
        Jest.test("Part 2 - Solve", (function () {
                var result = AOC2023_Day2$AdventOfCode.solvePart2(AOC2023_Day2_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 77607);
              }));
      }));

var data = AOC2023_Day2_Data$AdventOfCode.data;

var sampleData = AOC2023_Day2_Data_Sample$AdventOfCode.data;

var solvePart1 = AOC2023_Day2$AdventOfCode.solvePart1;

var solvePart2 = AOC2023_Day2$AdventOfCode.solvePart2;

export {
  data ,
  sampleData ,
  solvePart1 ,
  solvePart2 ,
}
/*  Not a pure module */
