// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Utils$AdventOfCode = require("../../Utils.bs.js");

function log(prim) {
  console.log(prim);
  
}

function make(__x) {
  return __x.split(",");
}

var Drawn = {
  make: make
};

function make$1(lines) {
  return Belt_Array.map(lines, (function (x) {
                return Belt_Array.map(Belt_Array.keep(x.split(" "), (function (s) {
                                  return s.length > 0;
                                })), (function (s) {
                              return Belt_Int.fromString(s.trim());
                            }));
              }));
}

var Board = {
  make: make$1
};

function make$2(lines) {
  return Belt_Array.map(lines, (function (b) {
                return make$1(Belt_Array.map(Utils$AdventOfCode.splitNewline(b), (function (prim) {
                                  return prim.trim();
                                })));
              }));
}

function dump(t) {
  return Belt_Array.forEach(t, (function (prim) {
                console.log(prim);
                
              }));
}

var Boards = {
  make: make$2,
  dump: dump
};

function part1(drawn, boards) {
  dump(boards);
  return [
          drawn,
          boards
        ];
}

function parse(data) {
  var lines = Belt_Array.map(Utils$AdventOfCode.splitDoubleNewline(data), (function (x) {
          return x.trim();
        }));
  var drawn = Belt_Option.getExn(Belt_Array.get(lines, 0)).split(",");
  var boards = make$2(Belt_Array.sliceToEnd(lines, 1));
  return [
          drawn,
          boards
        ];
}

function solvePart1(data) {
  var match = parse(data);
  return part1(match[0], match[1]);
}

function solvePart2(data) {
  return 2;
}

exports.log = log;
exports.Drawn = Drawn;
exports.Board = Board;
exports.Boards = Boards;
exports.part1 = part1;
exports.parse = parse;
exports.solvePart1 = solvePart1;
exports.solvePart2 = solvePart2;
/* No side effect */
