// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.mjs";
import * as AOC2020_Day13$AdventOfCode from "./AOC2020_Day13.mjs";
import * as AOC2020_Day13_Data$AdventOfCode from "./AOC2020_Day13_Data.mjs";
import * as AOC2020_Day13_Data_Sample$AdventOfCode from "./AOC2020_Day13_Data_Sample.mjs";

Jest.describe("2020 Day13", (function () {
        Jest.test("Part 1 - Sample Data", (function () {
                var result = AOC2020_Day13$AdventOfCode.solvePart1(AOC2020_Day13_Data_Sample$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 295);
              }));
        Jest.test("Part 1 - Solve", (function () {
                var result = AOC2020_Day13$AdventOfCode.solvePart1(AOC2020_Day13_Data$AdventOfCode.data);
                return Jest.Expect.toEqual(Jest.Expect.expect(result), 104);
              }));
        Jest.test("Part 2 - Solve", (function () {
                var result = AOC2020_Day13$AdventOfCode.solvePart2(AOC2020_Day13_Data$AdventOfCode.data);
                var expected = BigInt("842186186521918");
                return Jest.Expect.toEqual(Jest.Expect.expect(result), expected);
              }));
      }));

var data = AOC2020_Day13_Data$AdventOfCode.data;

var sampleData = AOC2020_Day13_Data_Sample$AdventOfCode.data;

export {
  data ,
  sampleData ,
}
/*  Not a pure module */
