// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AOC2022_Day2 from "./AOC2022_Day2.res.mjs";
import * as AOC2022_Day2_Data from "./AOC2022_Day2_Data.res.mjs";
import * as AOC2022_Day2_Data_Sample from "./AOC2022_Day2_Data_Sample.res.mjs";

Jest.describe("2022 Day2", () => {
  Jest.test("Part 1 - Sample Data", () => {
    let result = AOC2022_Day2.solvePart1(AOC2022_Day2_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 15);
  });
  Jest.test("Part 1 - Solve", () => {
    let result = AOC2022_Day2.solvePart1(AOC2022_Day2_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 11603);
  });
  Jest.test("Part 2 - Sample Data", () => {
    let result = AOC2022_Day2.solvePart2(AOC2022_Day2_Data_Sample.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 12);
  });
  Jest.test("Part 2 - Solve", () => {
    let result = AOC2022_Day2.solvePart2(AOC2022_Day2_Data.data);
    return Jest.Expect.toEqual(Jest.Expect.expect(result), 12725);
  });
});

let data = AOC2022_Day2_Data.data;

let sampleData = AOC2022_Day2_Data_Sample.data;

let solvePart1 = AOC2022_Day2.solvePart1;

let solvePart2 = AOC2022_Day2.solvePart2;

export {
  data,
  sampleData,
  solvePart1,
  solvePart2,
}
/*  Not a pure module */
