// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2022_Day2$AdventOfCode from "./AOC2022_Day2.mjs";
import * as AOC2022_Day2_Data$AdventOfCode from "./AOC2022_Day2_Data.mjs";
import * as AOC2022_Day2_Data_Sample$AdventOfCode from "./AOC2022_Day2_Data_Sample.mjs";

describe("2022 Day2", (function () {
        test("Part 1 - Sample Data", (function () {
                var result = AOC2022_Day2$AdventOfCode.solvePart1(AOC2022_Day2_Data_Sample$AdventOfCode.data);
                expect(result).toEqual(1);
              }));
        test("Part 1 - Solve", (function () {
                var result = AOC2022_Day2$AdventOfCode.solvePart1(AOC2022_Day2_Data$AdventOfCode.data);
                expect(result).toEqual(1);
              }));
        test("Part 2 - Sample Data", (function () {
                var result = AOC2022_Day2$AdventOfCode.solvePart2(AOC2022_Day2_Data_Sample$AdventOfCode.data);
                expect(result).toEqual(2);
              }));
        test("Part 2 - Solve", (function () {
                var result = AOC2022_Day2$AdventOfCode.solvePart2(AOC2022_Day2_Data$AdventOfCode.data);
                expect(result).toEqual(2);
              }));
      }));

var data = AOC2022_Day2_Data$AdventOfCode.data;

var sampleData = AOC2022_Day2_Data_Sample$AdventOfCode.data;

var solvePart1 = AOC2022_Day2$AdventOfCode.solvePart1;

var solvePart2 = AOC2022_Day2$AdventOfCode.solvePart2;

export {
  data ,
  sampleData ,
  solvePart1 ,
  solvePart2 ,
}
/*  Not a pure module */
