// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var AOC2018_Day4$AdventOfCode = require("./AOC2018_Day4.bs.js");
var AOC2018_Day4_Data$AdventOfCode = require("./AOC2018_Day4_Data.bs.js");
var AOC2018_Day4_Data_Sample$AdventOfCode = require("./AOC2018_Day4_Data_Sample.bs.js");

Jest.describe("2018 Day4", (function (param) {
        Jest.describe("Part 1", (function (param) {
                Jest.test("Solve Part 1 - sampleData", (function (param) {
                        var result = AOC2018_Day4$AdventOfCode.solvePart1(AOC2018_Day4_Data_Sample$AdventOfCode.data);
                        return Jest.Expect.toEqual(240, Jest.Expect.expect(result));
                      }));
                return Jest.test("Solve Part 1 - Data", (function (param) {
                              var result = AOC2018_Day4$AdventOfCode.solvePart1(AOC2018_Day4_Data$AdventOfCode.data);
                              return Jest.Expect.toEqual(48680, Jest.Expect.expect(result));
                            }));
              }));
        return Jest.describe("Part 2", (function (param) {
                      Jest.test("Solve Part 2 - sampleData", (function (param) {
                              var result = AOC2018_Day4$AdventOfCode.solvePart2(AOC2018_Day4_Data_Sample$AdventOfCode.data);
                              return Jest.Expect.toEqual(4455, Jest.Expect.expect(result));
                            }));
                      return Jest.test("Solve Part 2 - Data", (function (param) {
                                    var result = AOC2018_Day4$AdventOfCode.solvePart2(AOC2018_Day4_Data$AdventOfCode.data);
                                    return Jest.Expect.toEqual(94826, Jest.Expect.expect(result));
                                  }));
                    }));
      }));

var data = AOC2018_Day4_Data$AdventOfCode.data;

var sampleData = AOC2018_Day4_Data_Sample$AdventOfCode.data;

exports.data = data;
exports.sampleData = sampleData;
/*  Not a pure module */
