// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2021_Day1$AdventOfCode from "./AOC2021_Day1.mjs";
import * as AOC2021_Day1_Data$AdventOfCode from "./AOC2021_Day1_Data.mjs";
import * as AOC2021_Day1_Data_Sample$AdventOfCode from "./AOC2021_Day1_Data_Sample.mjs";

function log(prim) {
  console.log(prim);
}

var part1 = AOC2021_Day1$AdventOfCode.solvePart1(AOC2021_Day1_Data$AdventOfCode.data);

console.log("Part 1 Result");

console.log(part1);

var part2 = AOC2021_Day1$AdventOfCode.solvePart2(AOC2021_Day1_Data$AdventOfCode.data);

console.log("Part 2 Result");

console.log(part2);

var data = AOC2021_Day1_Data$AdventOfCode.data;

var sampleData = AOC2021_Day1_Data_Sample$AdventOfCode.data;

export {
  log ,
  data ,
  sampleData ,
  part1 ,
  part2 ,
}
/* part1 Not a pure module */
