// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "199\n            200\n            208\n            210\n            200\n            207\n            240\n            269\n            260\n            263";

export {
  data ,
}
/* No side effect */
