// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Stdlib__Map_Ext from "@dsiu/rescript-stdlib-fp/src/Stdlib__Map_Ext.res.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as Stdlib__Serializable from "@dsiu/rescript-stdlib-fp/src/Stdlib__Serializable.res.mjs";
import * as Stdlib__JSONSerializable from "@dsiu/rescript-stdlib-fp/src/Stdlib__JSONSerializable.res.mjs";

function MakeImpl(NodeC) {
  let addNode = (t, node) => {
    let match = NodeC.get(t, node);
    if (match !== undefined) {
      return;
    } else {
      return NodeC.set(t, node, NodeC.make());
    }
  };
  let hasNode = (t, node) => NodeC.has(t, node);
  let adjacent = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.has(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getAllNodes = t => Array.from(NodeC.keys(t));
  let neighbors = (t, node) => Array.from(NodeC.keys(Stdlib_Option.getOr(NodeC.get(t, node), NodeC.make())));
  let removeNode = (t, node) => {
    let children = neighbors(t, node);
    children.forEach(child => {
      let c = NodeC.get(t, child);
      if (c !== undefined) {
        NodeC.$$delete(Primitive_option.valFromOption(c), node);
        return;
      }
      
    });
    return NodeC.$$delete(t, node);
  };
  let addDirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addNode(t, a);
    addNode(t, b);
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.set(Primitive_option.valFromOption(ec), b, weight);
    }
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  };
  let addUndirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addDirectedEdge(t, a, b, Primitive_option.some(weight));
    addDirectedEdge(t, b, a, Primitive_option.some(weight));
  };
  let removeUndirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (!(
        ec !== undefined ? NodeC.$$delete(Primitive_option.valFromOption(ec), b) : false
      )) {
      return false;
    }
    let ec$1 = NodeC.get(t, b);
    if (ec$1 !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec$1), a);
    } else {
      return false;
    }
  };
  let removeDirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getWeight = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return Stdlib_Option.getOr(NodeC.get(Primitive_option.valFromOption(ec), b), undefined);
    }
    
  };
  return {
    make: NodeC.make,
    addNode: addNode,
    removeNode: removeNode,
    hasNode: hasNode,
    getAllNodes: getAllNodes,
    addUndirectedEdge: addUndirectedEdge,
    addDirectedEdge: addDirectedEdge,
    removeUndirectedEdge: removeUndirectedEdge,
    removeDirectedEdge: removeDirectedEdge,
    getWeight: getWeight,
    adjacent: adjacent,
    neighbors: neighbors
  };
}

function MakeWithPrimitive(T) {
  let NodeC = Stdlib__Map_Ext.MakeWithPrimitive(T);
  let addNode = (t, node) => {
    let match = NodeC.get(t, node);
    if (match !== undefined) {
      return;
    } else {
      return NodeC.set(t, node, NodeC.make());
    }
  };
  let hasNode = (t, node) => NodeC.has(t, node);
  let adjacent = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.has(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getAllNodes = t => Array.from(NodeC.keys(t));
  let neighbors = (t, node) => Array.from(NodeC.keys(Stdlib_Option.getOr(NodeC.get(t, node), NodeC.make())));
  let removeNode = (t, node) => {
    let children = neighbors(t, node);
    children.forEach(child => {
      let c = NodeC.get(t, child);
      if (c !== undefined) {
        NodeC.$$delete(Primitive_option.valFromOption(c), node);
        return;
      }
      
    });
    return NodeC.$$delete(t, node);
  };
  let addDirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addNode(t, a);
    addNode(t, b);
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.set(Primitive_option.valFromOption(ec), b, weight);
    }
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  };
  let addUndirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addDirectedEdge(t, a, b, Primitive_option.some(weight));
    addDirectedEdge(t, b, a, Primitive_option.some(weight));
  };
  let removeUndirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (!(
        ec !== undefined ? NodeC.$$delete(Primitive_option.valFromOption(ec), b) : false
      )) {
      return false;
    }
    let ec$1 = NodeC.get(t, b);
    if (ec$1 !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec$1), a);
    } else {
      return false;
    }
  };
  let removeDirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getWeight = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return Stdlib_Option.getOr(NodeC.get(Primitive_option.valFromOption(ec), b), undefined);
    }
    
  };
  return {
    make: NodeC.make,
    addNode: addNode,
    removeNode: removeNode,
    hasNode: hasNode,
    getAllNodes: getAllNodes,
    addUndirectedEdge: addUndirectedEdge,
    addDirectedEdge: addDirectedEdge,
    removeUndirectedEdge: removeUndirectedEdge,
    removeDirectedEdge: removeDirectedEdge,
    getWeight: getWeight,
    adjacent: adjacent,
    neighbors: neighbors
  };
}

function Make(Serializable) {
  let NodeC = Stdlib__Map_Ext.Make(Serializable);
  let addNode = (t, node) => {
    let match = NodeC.get(t, node);
    if (match !== undefined) {
      return;
    } else {
      return NodeC.set(t, node, NodeC.make());
    }
  };
  let hasNode = (t, node) => NodeC.has(t, node);
  let adjacent = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.has(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getAllNodes = t => Array.from(NodeC.keys(t));
  let neighbors = (t, node) => Array.from(NodeC.keys(Stdlib_Option.getOr(NodeC.get(t, node), NodeC.make())));
  let removeNode = (t, node) => {
    let children = neighbors(t, node);
    children.forEach(child => {
      let c = NodeC.get(t, child);
      if (c !== undefined) {
        NodeC.$$delete(Primitive_option.valFromOption(c), node);
        return;
      }
      
    });
    return NodeC.$$delete(t, node);
  };
  let addDirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addNode(t, a);
    addNode(t, b);
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.set(Primitive_option.valFromOption(ec), b, weight);
    }
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  };
  let addUndirectedEdge = (t, a, b, weightOpt) => {
    let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
    addDirectedEdge(t, a, b, Primitive_option.some(weight));
    addDirectedEdge(t, b, a, Primitive_option.some(weight));
  };
  let removeUndirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (!(
        ec !== undefined ? NodeC.$$delete(Primitive_option.valFromOption(ec), b) : false
      )) {
      return false;
    }
    let ec$1 = NodeC.get(t, b);
    if (ec$1 !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec$1), a);
    } else {
      return false;
    }
  };
  let removeDirectedEdge = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return NodeC.$$delete(Primitive_option.valFromOption(ec), b);
    } else {
      return false;
    }
  };
  let getWeight = (t, a, b) => {
    let ec = NodeC.get(t, a);
    if (ec !== undefined) {
      return Stdlib_Option.getOr(NodeC.get(Primitive_option.valFromOption(ec), b), undefined);
    }
    
  };
  return {
    make: NodeC.make,
    addNode: addNode,
    removeNode: removeNode,
    hasNode: hasNode,
    getAllNodes: getAllNodes,
    addUndirectedEdge: addUndirectedEdge,
    addDirectedEdge: addDirectedEdge,
    removeUndirectedEdge: removeUndirectedEdge,
    removeDirectedEdge: removeDirectedEdge,
    getWeight: getWeight,
    adjacent: adjacent,
    neighbors: neighbors
  };
}

let T = {};

let NodeC = Stdlib__Map_Ext.MakeWithPrimitive(T);

function addNode(t, node) {
  let match = NodeC.get(t, node);
  if (match !== undefined) {
    return;
  } else {
    return NodeC.set(t, node, NodeC.make());
  }
}

function hasNode(t, node) {
  return NodeC.has(t, node);
}

function adjacent(t, a, b) {
  let ec = NodeC.get(t, a);
  if (ec !== undefined) {
    return NodeC.has(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getAllNodes(t) {
  return Array.from(NodeC.keys(t));
}

function neighbors(t, node) {
  return Array.from(NodeC.keys(Stdlib_Option.getOr(NodeC.get(t, node), NodeC.make())));
}

function removeNode(t, node) {
  let children = neighbors(t, node);
  children.forEach(child => {
    let c = NodeC.get(t, child);
    if (c !== undefined) {
      NodeC.$$delete(Primitive_option.valFromOption(c), node);
      return;
    }
    
  });
  return NodeC.$$delete(t, node);
}

function addDirectedEdge(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addNode(t, a);
  addNode(t, b);
  let ec = NodeC.get(t, a);
  if (ec !== undefined) {
    return NodeC.set(Primitive_option.valFromOption(ec), b, weight);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function addUndirectedEdge(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addDirectedEdge(t, a, b, Primitive_option.some(weight));
  addDirectedEdge(t, b, a, Primitive_option.some(weight));
}

function removeUndirectedEdge(t, a, b) {
  let ec = NodeC.get(t, a);
  if (!(
      ec !== undefined ? NodeC.$$delete(Primitive_option.valFromOption(ec), b) : false
    )) {
    return false;
  }
  let ec$1 = NodeC.get(t, b);
  if (ec$1 !== undefined) {
    return NodeC.$$delete(Primitive_option.valFromOption(ec$1), a);
  } else {
    return false;
  }
}

function removeDirectedEdge(t, a, b) {
  let ec = NodeC.get(t, a);
  if (ec !== undefined) {
    return NodeC.$$delete(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getWeight(t, a, b) {
  let ec = NodeC.get(t, a);
  if (ec !== undefined) {
    return Stdlib_Option.getOr(NodeC.get(Primitive_option.valFromOption(ec), b), undefined);
  }
  
}

let String_make = NodeC.make;

let $$String = {
  make: String_make,
  addNode: addNode,
  removeNode: removeNode,
  hasNode: hasNode,
  getAllNodes: getAllNodes,
  addUndirectedEdge: addUndirectedEdge,
  addDirectedEdge: addDirectedEdge,
  removeUndirectedEdge: removeUndirectedEdge,
  removeDirectedEdge: removeDirectedEdge,
  getWeight: getWeight,
  adjacent: adjacent,
  neighbors: neighbors
};

function Make$1(A) {
  return B => {
    let Serializable = Stdlib__Serializable.MakeTuple2(A)(B);
    let NodeC = Stdlib__Map_Ext.Make(Serializable);
    let addNode = (t, node) => {
      let match = NodeC.get(t, node);
      if (match !== undefined) {
        return;
      } else {
        return NodeC.set(t, node, NodeC.make());
      }
    };
    let hasNode = (t, node) => NodeC.has(t, node);
    let adjacent = (t, a, b) => {
      let ec = NodeC.get(t, a);
      if (ec !== undefined) {
        return NodeC.has(Primitive_option.valFromOption(ec), b);
      } else {
        return false;
      }
    };
    let getAllNodes = t => Array.from(NodeC.keys(t));
    let neighbors = (t, node) => Array.from(NodeC.keys(Stdlib_Option.getOr(NodeC.get(t, node), NodeC.make())));
    let removeNode = (t, node) => {
      let children = neighbors(t, node);
      children.forEach(child => {
        let c = NodeC.get(t, child);
        if (c !== undefined) {
          NodeC.$$delete(Primitive_option.valFromOption(c), node);
          return;
        }
        
      });
      return NodeC.$$delete(t, node);
    };
    let addDirectedEdge = (t, a, b, weightOpt) => {
      let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
      addNode(t, a);
      addNode(t, b);
      let ec = NodeC.get(t, a);
      if (ec !== undefined) {
        return NodeC.set(Primitive_option.valFromOption(ec), b, weight);
      }
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    };
    let addUndirectedEdge = (t, a, b, weightOpt) => {
      let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
      addDirectedEdge(t, a, b, Primitive_option.some(weight));
      addDirectedEdge(t, b, a, Primitive_option.some(weight));
    };
    let removeUndirectedEdge = (t, a, b) => {
      let ec = NodeC.get(t, a);
      if (!(
          ec !== undefined ? NodeC.$$delete(Primitive_option.valFromOption(ec), b) : false
        )) {
        return false;
      }
      let ec$1 = NodeC.get(t, b);
      if (ec$1 !== undefined) {
        return NodeC.$$delete(Primitive_option.valFromOption(ec$1), a);
      } else {
        return false;
      }
    };
    let removeDirectedEdge = (t, a, b) => {
      let ec = NodeC.get(t, a);
      if (ec !== undefined) {
        return NodeC.$$delete(Primitive_option.valFromOption(ec), b);
      } else {
        return false;
      }
    };
    let getWeight = (t, a, b) => {
      let ec = NodeC.get(t, a);
      if (ec !== undefined) {
        return Stdlib_Option.getOr(NodeC.get(Primitive_option.valFromOption(ec), b), undefined);
      }
      
    };
    return {
      make: NodeC.make,
      addNode: addNode,
      removeNode: removeNode,
      hasNode: hasNode,
      getAllNodes: getAllNodes,
      addUndirectedEdge: addUndirectedEdge,
      addDirectedEdge: addDirectedEdge,
      removeUndirectedEdge: removeUndirectedEdge,
      removeDirectedEdge: removeDirectedEdge,
      getWeight: getWeight,
      adjacent: adjacent,
      neighbors: neighbors
    };
  };
}

let Serializable = Stdlib__Serializable.MakeTuple2(Stdlib__JSONSerializable.Int)(Stdlib__JSONSerializable.Int);

let NodeC$1 = Stdlib__Map_Ext.Make(Serializable);

function addNode$1(t, node) {
  let match = NodeC$1.get(t, node);
  if (match !== undefined) {
    return;
  } else {
    return NodeC$1.set(t, node, NodeC$1.make());
  }
}

function hasNode$1(t, node) {
  return NodeC$1.has(t, node);
}

function adjacent$1(t, a, b) {
  let ec = NodeC$1.get(t, a);
  if (ec !== undefined) {
    return NodeC$1.has(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getAllNodes$1(t) {
  return Array.from(NodeC$1.keys(t));
}

function neighbors$1(t, node) {
  return Array.from(NodeC$1.keys(Stdlib_Option.getOr(NodeC$1.get(t, node), NodeC$1.make())));
}

function removeNode$1(t, node) {
  let children = neighbors$1(t, node);
  children.forEach(child => {
    let c = NodeC$1.get(t, child);
    if (c !== undefined) {
      NodeC$1.$$delete(Primitive_option.valFromOption(c), node);
      return;
    }
    
  });
  return NodeC$1.$$delete(t, node);
}

function addDirectedEdge$1(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addNode$1(t, a);
  addNode$1(t, b);
  let ec = NodeC$1.get(t, a);
  if (ec !== undefined) {
    return NodeC$1.set(Primitive_option.valFromOption(ec), b, weight);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function addUndirectedEdge$1(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addDirectedEdge$1(t, a, b, Primitive_option.some(weight));
  addDirectedEdge$1(t, b, a, Primitive_option.some(weight));
}

function removeUndirectedEdge$1(t, a, b) {
  let ec = NodeC$1.get(t, a);
  if (!(
      ec !== undefined ? NodeC$1.$$delete(Primitive_option.valFromOption(ec), b) : false
    )) {
    return false;
  }
  let ec$1 = NodeC$1.get(t, b);
  if (ec$1 !== undefined) {
    return NodeC$1.$$delete(Primitive_option.valFromOption(ec$1), a);
  } else {
    return false;
  }
}

function removeDirectedEdge$1(t, a, b) {
  let ec = NodeC$1.get(t, a);
  if (ec !== undefined) {
    return NodeC$1.$$delete(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getWeight$1(t, a, b) {
  let ec = NodeC$1.get(t, a);
  if (ec !== undefined) {
    return Stdlib_Option.getOr(NodeC$1.get(Primitive_option.valFromOption(ec), b), undefined);
  }
  
}

let IntInt_make = NodeC$1.make;

let IntInt = {
  make: IntInt_make,
  addNode: addNode$1,
  removeNode: removeNode$1,
  hasNode: hasNode$1,
  getAllNodes: getAllNodes$1,
  addUndirectedEdge: addUndirectedEdge$1,
  addDirectedEdge: addDirectedEdge$1,
  removeUndirectedEdge: removeUndirectedEdge$1,
  removeDirectedEdge: removeDirectedEdge$1,
  getWeight: getWeight$1,
  adjacent: adjacent$1,
  neighbors: neighbors$1
};

let Serializable$1 = Stdlib__Serializable.MakeTuple2(Stdlib__JSONSerializable.$$String)(Stdlib__JSONSerializable.Int);

let NodeC$2 = Stdlib__Map_Ext.Make(Serializable$1);

function addNode$2(t, node) {
  let match = NodeC$2.get(t, node);
  if (match !== undefined) {
    return;
  } else {
    return NodeC$2.set(t, node, NodeC$2.make());
  }
}

function hasNode$2(t, node) {
  return NodeC$2.has(t, node);
}

function adjacent$2(t, a, b) {
  let ec = NodeC$2.get(t, a);
  if (ec !== undefined) {
    return NodeC$2.has(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getAllNodes$2(t) {
  return Array.from(NodeC$2.keys(t));
}

function neighbors$2(t, node) {
  return Array.from(NodeC$2.keys(Stdlib_Option.getOr(NodeC$2.get(t, node), NodeC$2.make())));
}

function removeNode$2(t, node) {
  let children = neighbors$2(t, node);
  children.forEach(child => {
    let c = NodeC$2.get(t, child);
    if (c !== undefined) {
      NodeC$2.$$delete(Primitive_option.valFromOption(c), node);
      return;
    }
    
  });
  return NodeC$2.$$delete(t, node);
}

function addDirectedEdge$2(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addNode$2(t, a);
  addNode$2(t, b);
  let ec = NodeC$2.get(t, a);
  if (ec !== undefined) {
    return NodeC$2.set(Primitive_option.valFromOption(ec), b, weight);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function addUndirectedEdge$2(t, a, b, weightOpt) {
  let weight = weightOpt !== undefined ? Primitive_option.valFromOption(weightOpt) : undefined;
  addDirectedEdge$2(t, a, b, Primitive_option.some(weight));
  addDirectedEdge$2(t, b, a, Primitive_option.some(weight));
}

function removeUndirectedEdge$2(t, a, b) {
  let ec = NodeC$2.get(t, a);
  if (!(
      ec !== undefined ? NodeC$2.$$delete(Primitive_option.valFromOption(ec), b) : false
    )) {
    return false;
  }
  let ec$1 = NodeC$2.get(t, b);
  if (ec$1 !== undefined) {
    return NodeC$2.$$delete(Primitive_option.valFromOption(ec$1), a);
  } else {
    return false;
  }
}

function removeDirectedEdge$2(t, a, b) {
  let ec = NodeC$2.get(t, a);
  if (ec !== undefined) {
    return NodeC$2.$$delete(Primitive_option.valFromOption(ec), b);
  } else {
    return false;
  }
}

function getWeight$2(t, a, b) {
  let ec = NodeC$2.get(t, a);
  if (ec !== undefined) {
    return Stdlib_Option.getOr(NodeC$2.get(Primitive_option.valFromOption(ec), b), undefined);
  }
  
}

let StringInt_make = NodeC$2.make;

let StringInt = {
  make: StringInt_make,
  addNode: addNode$2,
  removeNode: removeNode$2,
  hasNode: hasNode$2,
  getAllNodes: getAllNodes$2,
  addUndirectedEdge: addUndirectedEdge$2,
  addDirectedEdge: addDirectedEdge$2,
  removeUndirectedEdge: removeUndirectedEdge$2,
  removeDirectedEdge: removeDirectedEdge$2,
  getWeight: getWeight$2,
  adjacent: adjacent$2,
  neighbors: neighbors$2
};

let Tuple2 = {
  Make: Make$1,
  IntInt: IntInt,
  StringInt: StringInt
};

let Node = {
  $$String: $$String,
  Tuple2: Tuple2
};

let Serializable$2;

let JSONSerializable;

export {
  Serializable$2 as Serializable,
  JSONSerializable,
  MakeImpl,
  MakeWithPrimitive,
  Make,
  Node,
}
/* NodeC Not a pure module */
