// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function make(param, e) {
  var y = param[1];
  return Belt_Array.makeBy(param[0], (function (param) {
                return Belt_Array.make(y, e);
              }));
}

function lengthX(t) {
  return t.length;
}

function lengthY(t) {
  return Belt_Array.getExn(t, 0).length;
}

function set(t, param, e) {
  var x = Belt_Array.get(t, param[0]);
  if (x !== undefined) {
    return Belt_Array.set(x, param[1], e);
  } else {
    return false;
  }
}

function get(t, param) {
  var x = Belt_Array.get(t, param[0]);
  if (x !== undefined) {
    return Belt_Array.get(x, param[1]);
  }
  
}

var getXEquals = Belt_Array.get;

function getYEquals(t, y) {
  var ret = Belt_Array.reduce(t, [], (function (a, ys) {
          return Belt_Array.concat(a, [Belt_Array.getExn(ys, y)]);
        }));
  if (ret.length === t.length) {
    return ret;
  }
  
}

function map(t, f) {
  return Belt_Array.map(t, (function (x) {
                return Belt_Array.map(x, f);
              }));
}

exports.make = make;
exports.lengthX = lengthX;
exports.lengthY = lengthY;
exports.set = set;
exports.get = get;
exports.getXEquals = getXEquals;
exports.getYEquals = getYEquals;
exports.map = map;
/* No side effect */
