// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TableclothInt from "@dsiu/rescript-stdlib-fp/src/Tablecloth/TableclothInt.mjs";
import * as TableclothTuple3 from "@dsiu/rescript-stdlib-fp/src/Tablecloth/TableclothTuple3.mjs";
import * as TableclothComparator from "@dsiu/rescript-stdlib-fp/src/Tablecloth/TableclothComparator.mjs";

function compare(param) {
  return function (param$1) {
    var param$2 = TableclothInt.compare;
    var param$3 = TableclothInt.compare;
    var param$4 = TableclothInt.compare;
    return TableclothTuple3.compare(param, param$1, param$2, param$3, param$4);
  };
}

var include = TableclothComparator.Make({
      compare: compare
    });

function add(param, param$1) {
  return [
          param[0] + param$1[0] | 0,
          param[1] + param$1[1] | 0,
          param[2] + param$1[2] | 0
        ];
}

function mul(param, x) {
  return [
          Math.imul(param[0], x),
          Math.imul(param[1], x),
          Math.imul(param[2], x)
        ];
}

var TC;

var comparator = include.comparator;

export {
  TC ,
  compare ,
  comparator ,
  add ,
  mul ,
}
/* include Not a pure module */
