// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JS_Debug$AdventOfCode from "./JS_Debug.mjs";

let Log = JS_Debug$AdventOfCode.make("JS_Debug_Run-AdventOfCode");

let LogR = JS_Debug$AdventOfCode.make("Logger Run");

Log.debug("Starting");

LogR.debug("Starting");

let error = {
  a: 1,
  b: 2
};

Log.debug("end");

LogR.debug("end");

let b = {
  propb: "valueb"
};

export {
  Log,
  LogR,
  error,
  b,
}
/* Log Not a pure module */
