// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JS_Debug$AdventOfCode from "./JS_Debug.mjs";

var Log = JS_Debug$AdventOfCode.make("JS_Debug_Run-AdventOfCode");

var LogR = JS_Debug$AdventOfCode.make("Logger Run");

Log.debug("Starting");

LogR.debug("Starting");

var error = {
  a: 1,
  b: 2
};

Log.debug("end");

LogR.debug("end");

var b = {
  propb: "valueb"
};

export {
  Log ,
  LogR ,
  error ,
  b ,
}
/* Log Not a pure module */
