// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Utils$AdventOfCode = require("./Utils.bs.js");

function log(prim) {
  console.log(prim);
  
}

Belt_Array.forEach([
      -1,
      -1,
      1,
      1
    ], (function (x) {
        var prim = Utils$AdventOfCode.int32ToUint32(x);
        console.log(prim);
        
      }));

exports.log = log;
/*  Not a pure module */
