// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AdjacencyList from "../src/AdjacencyList.res.mjs";

Jest.describe("AdjacencyList String Implementation", () => {
  let graph = {
    contents: AdjacencyList.Node.$$String.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList.Node.$$String.make();
    AdjacencyList.Node.$$String.addNode(graph.contents, "A");
    AdjacencyList.Node.$$String.addNode(graph.contents, "B");
    AdjacencyList.Node.$$String.addNode(graph.contents, "C");
    AdjacencyList.Node.$$String.addNode(graph.contents, "D");
    AdjacencyList.Node.$$String.addNode(graph.contents, "E");
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "A", "B", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "B", "C", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "C", "D", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "D", "E", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "E", "A", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "A", "C", undefined);
    AdjacencyList.Node.$$String.addDirectedEdge(graph.contents, "B", "D", undefined);
  });
  Jest.test("add vertex", () => {
    AdjacencyList.Node.$$String.addNode(graph.contents, "F");
    return Jest.Expect.toEqual(Jest.Expect.expect(AdjacencyList.Node.$$String.hasNode(graph.contents, "F")), true);
  });
  Jest.test("add edge", () => Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.$$String.adjacent(graph.contents, "A", "B")), true));
  Jest.test("remove edge", () => {
    AdjacencyList.Node.$$String.removeDirectedEdge(graph.contents, "A", "B");
    return Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.$$String.adjacent(graph.contents, "A", "B")), false);
  });
  let neighbors_tests_0 = [
    "A",
    [
      "B",
      "C"
    ]
  ];
  let neighbors_tests_1 = {
    hd: [
      "B",
      [
        "C",
        "D"
      ]
    ],
    tl: {
      hd: [
        "C",
        ["D"]
      ],
      tl: {
        hd: [
          "D",
          ["E"]
        ],
        tl: {
          hd: [
            "E",
            ["A"]
          ],
          tl: /* [] */0
        }
      }
    }
  };
  let neighbors_tests = {
    hd: neighbors_tests_0,
    tl: neighbors_tests_1
  };
  Jest.testAll("neighbors", neighbors_tests, param => Jest.Expect.toEqual(Jest.Expect.expect(AdjacencyList.Node.$$String.neighbors(graph.contents, param[0])), param[1]));
  Jest.test("remove vertex", () => {
    AdjacencyList.Node.$$String.removeNode(graph.contents, "A");
    return Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.$$String.hasNode(graph.contents, "A")), false);
  });
});

Jest.describe("AdjacencyList Tuple Implementation", () => {
  let graph = {
    contents: AdjacencyList.Node.Tuple2.StringInt.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList.Node.Tuple2.StringInt.make();
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "A",
      1
    ]);
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "B",
      2
    ]);
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "C",
      3
    ]);
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "D",
      4
    ]);
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "E",
      5
    ]);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "A",
      1
    ], [
      "B",
      2
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "B",
      2
    ], [
      "C",
      3
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "C",
      3
    ], [
      "D",
      4
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "D",
      4
    ], [
      "E",
      5
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "E",
      5
    ], [
      "A",
      1
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "A",
      1
    ], [
      "C",
      3
    ], undefined);
    AdjacencyList.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "B",
      2
    ], [
      "D",
      4
    ], undefined);
  });
  Jest.test("add vertex", () => {
    AdjacencyList.Node.Tuple2.StringInt.addNode(graph.contents, [
      "F",
      6
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(AdjacencyList.Node.Tuple2.StringInt.hasNode(graph.contents, [
      "F",
      6
    ])), true);
  });
  Jest.test("add edge", () => Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.Tuple2.StringInt.adjacent(graph.contents, [
    "A",
    1
  ], [
    "B",
    2
  ])), true));
  Jest.test("remove edge", () => {
    AdjacencyList.Node.Tuple2.StringInt.removeDirectedEdge(graph.contents, [
      "A",
      1
    ], [
      "B",
      2
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.Tuple2.StringInt.adjacent(graph.contents, [
      "A",
      1
    ], [
      "B",
      2
    ])), false);
  });
  let neighbors_tests_0 = [
    [
      "A",
      1
    ],
    [
      [
        "B",
        2
      ],
      [
        "C",
        3
      ]
    ]
  ];
  let neighbors_tests_1 = {
    hd: [
      [
        "B",
        2
      ],
      [
        [
          "C",
          3
        ],
        [
          "D",
          4
        ]
      ]
    ],
    tl: {
      hd: [
        [
          "C",
          3
        ],
        [[
            "D",
            4
          ]]
      ],
      tl: {
        hd: [
          [
            "D",
            4
          ],
          [[
              "E",
              5
            ]]
        ],
        tl: {
          hd: [
            [
              "E",
              5
            ],
            [[
                "A",
                1
              ]]
          ],
          tl: /* [] */0
        }
      }
    }
  };
  let neighbors_tests = {
    hd: neighbors_tests_0,
    tl: neighbors_tests_1
  };
  Jest.testAll("neighbors", neighbors_tests, param => Jest.Expect.toEqual(Jest.Expect.expect(AdjacencyList.Node.Tuple2.StringInt.neighbors(graph.contents, param[0])), param[1]));
  Jest.test("remove vertex", () => {
    AdjacencyList.Node.Tuple2.StringInt.removeNode(graph.contents, [
      "A",
      1
    ]);
    return Jest.Expect.toBe(Jest.Expect.expect(AdjacencyList.Node.Tuple2.StringInt.hasNode(graph.contents, [
      "A",
      1
    ])), false);
  });
});

let StringAdjList;

let TupleAdjList;

export {
  StringAdjList,
  TupleAdjList,
}
/*  Not a pure module */
