// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Array2D$AdventOfCode = require("../src/Array2D.bs.js");
var AOC2020_Day4_Data$AdventOfCode = require("../src/2020/Day4/AOC2020_Day4_Data.bs.js");
var AOC2020_Day4_Data_Test$AdventOfCode = require("../src/2020/Day4/AOC2020_Day4_Data_Test.bs.js");

Jest.describe("Array2D - make / set / get", (function (param) {
        Jest.test("make - int", (function (param) {
                var a = Array2D$AdventOfCode.make([
                      2,
                      2
                    ], -1);
                [
                  Array2D$AdventOfCode.set(a, [
                        0,
                        0
                      ], 4),
                  Array2D$AdventOfCode.set(a, [
                        0,
                        1
                      ], 5),
                  Array2D$AdventOfCode.set(a, [
                        1,
                        0
                      ], 6),
                  Array2D$AdventOfCode.set(a, [
                        1,
                        1
                      ], 7)
                ];
                var expected = [
                  [
                    4,
                    5
                  ],
                  [
                    6,
                    7
                  ]
                ];
                return Jest.Expect.toEqual(expected, Jest.Expect.expect(a));
              }));
        Jest.test("make - string", (function (param) {
                var a = Array2D$AdventOfCode.make([
                      2,
                      2
                    ], "");
                [
                  Array2D$AdventOfCode.set(a, [
                        0,
                        0
                      ], "a"),
                  Array2D$AdventOfCode.set(a, [
                        0,
                        1
                      ], "b"),
                  Array2D$AdventOfCode.set(a, [
                        1,
                        0
                      ], "c"),
                  Array2D$AdventOfCode.set(a, [
                        1,
                        1
                      ], "d")
                ];
                var expected = [
                  [
                    "a",
                    "b"
                  ],
                  [
                    "c",
                    "d"
                  ]
                ];
                return Jest.Expect.toEqual(expected, Jest.Expect.expect(a));
              }));
        return Jest.test("get - string", (function (param) {
                      var a = Array2D$AdventOfCode.make([
                            2,
                            2
                          ], "");
                      [
                        Array2D$AdventOfCode.set(a, [
                              0,
                              0
                            ], "e"),
                        Array2D$AdventOfCode.set(a, [
                              0,
                              1
                            ], "f"),
                        Array2D$AdventOfCode.set(a, [
                              1,
                              0
                            ], "g"),
                        Array2D$AdventOfCode.set(a, [
                              1,
                              1
                            ], "h")
                      ];
                      var result = [
                        Belt_Option.getExn(Array2D$AdventOfCode.get(a, [
                                  0,
                                  0
                                ])),
                        Belt_Option.getExn(Array2D$AdventOfCode.get(a, [
                                  0,
                                  1
                                ])),
                        Belt_Option.getExn(Array2D$AdventOfCode.get(a, [
                                  1,
                                  0
                                ])),
                        Belt_Option.getExn(Array2D$AdventOfCode.get(a, [
                                  1,
                                  1
                                ]))
                      ];
                      var expected = [
                        "e",
                        "f",
                        "g",
                        "h"
                      ];
                      return Jest.Expect.toEqual(expected, Jest.Expect.expect(result));
                    }));
      }));

Jest.describe("Array2D - keep / map", (function (param) {
        var a = Array2D$AdventOfCode.make([
              2,
              2
            ], -1);
        [
          Array2D$AdventOfCode.set(a, [
                0,
                0
              ], 4),
          Array2D$AdventOfCode.set(a, [
                0,
                1
              ], 5),
          Array2D$AdventOfCode.set(a, [
                1,
                0
              ], 6),
          Array2D$AdventOfCode.set(a, [
                1,
                1
              ], 7)
        ];
        Jest.test("keep - int", (function (param) {
                var result = Array2D$AdventOfCode.keep(a, (function (x) {
                        return 0 === x % 2;
                      }));
                var expected = [
                  [4],
                  [6]
                ];
                return Jest.Expect.toEqual(expected, Jest.Expect.expect(result));
              }));
        return Jest.test("map - int", (function (param) {
                      var result = Array2D$AdventOfCode.map(a, (function (x) {
                              return (x << 1);
                            }));
                      var expected = [
                        [
                          8,
                          10
                        ],
                        [
                          12,
                          14
                        ]
                      ];
                      return Jest.Expect.toEqual(expected, Jest.Expect.expect(result));
                    }));
      }));

var data = AOC2020_Day4_Data$AdventOfCode.data;

var testData = AOC2020_Day4_Data_Test$AdventOfCode.data;

exports.data = data;
exports.testData = testData;
/*  Not a pure module */
