// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as AStar$AdventOfCode from "../src/AStar.res.mjs";
import * as AdjacencyList$AdventOfCode from "../src/AdjacencyList.res.mjs";

function log(prim) {
  console.log(prim);
}

function log2(prim0, prim1) {
  console.log(prim0, prim1);
}

Jest.describe("AStar Algorithm with string", () => {
  let NodeMap = AdjacencyList$AdventOfCode.Node.$$String.nodeMap;
  let NodeSet = AdjacencyList$AdventOfCode.Node.$$String.nodeSet;
  let AStar = AStar$AdventOfCode.AStar({})(NodeMap)(NodeSet);
  let graph = {
    contents: AdjacencyList$AdventOfCode.Node.$$String.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "2", 7);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "3", 9);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "6", 14);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "2", "3", 10);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "2", "4", 15);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "3", "4", 11);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "3", "6", 2);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "4", "5", 6);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "5", "6", 9);
  });
  let heuristic = (_a, _b) => 0.0;
  let cost = (a, b) => {
    let weight = AdjacencyList$AdventOfCode.Node.$$String.getWeight(graph.contents, a, b);
    if (weight !== undefined) {
      return weight;
    }
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  };
  let neighbors = node => AdjacencyList$AdventOfCode.Node.$$String.neighbors(graph.contents, node);
  Jest.test("handles unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "7");
    let path = AStar.aStar("1", "7", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("returns correct path", () => {
    let path = AStar.aStar("1", "5", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      "1",
      "3",
      "4",
      "5"
    ]);
  });
  Jest.test("returns None for unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "7");
    let path = AStar.aStar("1", "7", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  let shortestPathsTestData_0 = [
    "1",
    ["1"]
  ];
  let shortestPathsTestData_1 = {
    hd: [
      "2",
      [
        "1",
        "2"
      ]
    ],
    tl: {
      hd: [
        "3",
        [
          "1",
          "3"
        ]
      ],
      tl: {
        hd: [
          "4",
          [
            "1",
            "3",
            "4"
          ]
        ],
        tl: {
          hd: [
            "5",
            [
              "1",
              "3",
              "4",
              "5"
            ]
          ],
          tl: {
            hd: [
              "6",
              [
                "1",
                "3",
                "6"
              ]
            ],
            tl: /* [] */0
          }
        }
      }
    }
  };
  let shortestPathsTestData = {
    hd: shortestPathsTestData_0,
    tl: shortestPathsTestData_1
  };
  Jest.testAll("returns correct paths for all nodes", shortestPathsTestData, param => {
    let paths = AStar.aStar("1", param[0], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(paths), param[1]);
  });
  Jest.test("handles empty graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    let path = AStar.aStar("1", "2", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("handles single node graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "1");
    let path = AStar.aStar("1", "1", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), ["1"]);
  });
  Jest.test("handles disconnected graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "1");
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "2");
    let path = AStar.aStar("1", "2", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("handles negative weights", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "2", -1);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "2", "3", -1);
    let path = AStar.aStar("1", "3", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      "1",
      "2",
      "3"
    ]);
  });
  Jest.test("works with different heuristic functions", () => {
    let heuristic = (_a, _b) => 1.0;
    let path = AStar.aStar("1", "5", neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      "1",
      "3",
      "4",
      "5"
    ]);
  });
});

Jest.describe("AStar Algorithm with Tuple2 (string,int)", () => {
  let NodeMap = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.nodeMap;
  let NodeSet = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.nodeSet;
  let AStar = AStar$AdventOfCode.AStar({})(NodeMap)(NodeSet);
  let graph = {
    contents: AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "2",
      2
    ], 7);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "3",
      3
    ], 9);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "6",
      6
    ], 14);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "2",
      2
    ], [
      "3",
      3
    ], 10);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "2",
      2
    ], [
      "4",
      4
    ], 15);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "3",
      3
    ], [
      "4",
      4
    ], 11);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "3",
      3
    ], [
      "6",
      6
    ], 2);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "4",
      4
    ], [
      "5",
      5
    ], 6);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "5",
      5
    ], [
      "6",
      6
    ], 9);
  });
  let heuristic = (_a, _b) => 0.0;
  let cost = (a, b) => {
    let weight = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.getWeight(graph.contents, a, b);
    if (weight !== undefined) {
      return weight;
    }
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  };
  let neighbors = node => AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.neighbors(graph.contents, node);
  Jest.test("handles unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "7",
      7
    ]);
    let path = AStar.aStar([
      "1",
      1
    ], [
      "7",
      7
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("returns correct path", () => {
    let path = AStar.aStar([
      "1",
      1
    ], [
      "5",
      5
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      [
        "1",
        1
      ],
      [
        "3",
        3
      ],
      [
        "4",
        4
      ],
      [
        "5",
        5
      ]
    ]);
  });
  Jest.test("returns None for unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "7",
      7
    ]);
    let path = AStar.aStar([
      "1",
      1
    ], [
      "7",
      7
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  let shortestPathsTestData_0 = [
    [
      "1",
      1
    ],
    [[
        "1",
        1
      ]]
  ];
  let shortestPathsTestData_1 = {
    hd: [
      [
        "2",
        2
      ],
      [
        [
          "1",
          1
        ],
        [
          "2",
          2
        ]
      ]
    ],
    tl: {
      hd: [
        [
          "3",
          3
        ],
        [
          [
            "1",
            1
          ],
          [
            "3",
            3
          ]
        ]
      ],
      tl: {
        hd: [
          [
            "4",
            4
          ],
          [
            [
              "1",
              1
            ],
            [
              "3",
              3
            ],
            [
              "4",
              4
            ]
          ]
        ],
        tl: {
          hd: [
            [
              "5",
              5
            ],
            [
              [
                "1",
                1
              ],
              [
                "3",
                3
              ],
              [
                "4",
                4
              ],
              [
                "5",
                5
              ]
            ]
          ],
          tl: {
            hd: [
              [
                "6",
                6
              ],
              [
                [
                  "1",
                  1
                ],
                [
                  "3",
                  3
                ],
                [
                  "6",
                  6
                ]
              ]
            ],
            tl: /* [] */0
          }
        }
      }
    }
  };
  let shortestPathsTestData = {
    hd: shortestPathsTestData_0,
    tl: shortestPathsTestData_1
  };
  Jest.testAll("returns correct paths for all nodes", shortestPathsTestData, param => {
    let paths = AStar.aStar([
      "1",
      1
    ], param[0], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(paths), param[1]);
  });
  Jest.test("handles empty graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    let path = AStar.aStar([
      "1",
      1
    ], [
      "2",
      2
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("handles single node graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "1",
      1
    ]);
    let path = AStar.aStar([
      "1",
      1
    ], [
      "1",
      1
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [[
        "1",
        1
      ]]);
  });
  Jest.test("handles disconnected graph", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "1",
      1
    ]);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "2",
      2
    ]);
    let path = AStar.aStar([
      "1",
      1
    ], [
      "2",
      2
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  Jest.test("handles negative weights", () => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "2",
      2
    ], -1);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "2",
      2
    ], [
      "3",
      3
    ], -1);
    let path = AStar.aStar([
      "1",
      1
    ], [
      "3",
      3
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      [
        "1",
        1
      ],
      [
        "2",
        2
      ],
      [
        "3",
        3
      ]
    ]);
  });
  Jest.test("works with different heuristic functions", () => {
    let heuristic = (_a, _b) => 1.0;
    let path = AStar.aStar([
      "1",
      1
    ], [
      "5",
      5
    ], neighbors, cost, heuristic);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      [
        "1",
        1
      ],
      [
        "3",
        3
      ],
      [
        "4",
        4
      ],
      [
        "5",
        5
      ]
    ]);
  });
});

let StringAdjList;

let TupleAdjList;

export {
  log,
  log2,
  StringAdjList,
  TupleAdjList,
}
/*  Not a pure module */
