// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Dijkstra$AdventOfCode from "../src/Dijkstra.res.mjs";
import * as AdjacencyList$AdventOfCode from "../src/AdjacencyList.res.mjs";

Jest.describe("Dijkstra Algorithm with StringAdjList", () => {
  let NodeMap = AdjacencyList$AdventOfCode.Node.$$String.nodeMap;
  let Dijkstra = Dijkstra$AdventOfCode.Dijkstra(AdjacencyList$AdventOfCode.Node.$$String)(NodeMap);
  let graph = {
    contents: AdjacencyList$AdventOfCode.Node.$$String.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList$AdventOfCode.Node.$$String.make();
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "2", 7);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "3", 9);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "1", "6", 14);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "2", "3", 10);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "2", "4", 15);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "3", "4", 11);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "3", "6", 2);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "4", "5", 6);
    AdjacencyList$AdventOfCode.Node.$$String.addDirectedEdge(graph.contents, "5", "6", 9);
  });
  Jest.testAll("calculates correct shortest distance", {
    hd: [
      "1",
      0
    ],
    tl: {
      hd: [
        "2",
        7
      ],
      tl: {
        hd: [
          "3",
          9
        ],
        tl: {
          hd: [
            "4",
            20
          ],
          tl: {
            hd: [
              "5",
              26
            ],
            tl: {
              hd: [
                "6",
                11
              ],
              tl: /* [] */0
            }
          }
        }
      }
    }
  }, param => {
    let match = Dijkstra.dijkstra(graph.contents, "1");
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(match[0], param[0])), param[1]);
  });
  Jest.test("handles unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "7");
    let match = Dijkstra.dijkstra(graph.contents, "1");
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(match[0], "7")), undefined);
  });
  Jest.test("returns correct path", () => {
    let path = Dijkstra.shortestPath(graph.contents, "1", "5");
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      "1",
      "3",
      "4",
      "5"
    ]);
  });
  Jest.test("returns None for unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.$$String.addNode(graph.contents, "7");
    let path = Dijkstra.shortestPath(graph.contents, "1", "7");
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  let shortestPathsTestData_0 = [
    "1",
    ["1"]
  ];
  let shortestPathsTestData_1 = {
    hd: [
      "2",
      [
        "1",
        "2"
      ]
    ],
    tl: {
      hd: [
        "3",
        [
          "1",
          "3"
        ]
      ],
      tl: {
        hd: [
          "4",
          [
            "1",
            "3",
            "4"
          ]
        ],
        tl: {
          hd: [
            "5",
            [
              "1",
              "3",
              "4",
              "5"
            ]
          ],
          tl: {
            hd: [
              "6",
              [
                "1",
                "3",
                "6"
              ]
            ],
            tl: /* [] */0
          }
        }
      }
    }
  };
  let shortestPathsTestData = {
    hd: shortestPathsTestData_0,
    tl: shortestPathsTestData_1
  };
  Jest.testAll("returns correct paths for all nodes", shortestPathsTestData, param => {
    let paths = Dijkstra.shortestPaths(graph.contents, "1");
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(paths, param[0])), param[1]);
  });
});

Jest.describe("Dijkstra Algorithm with TupleAdjList", () => {
  let NodeMap = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.nodeMap;
  let Dijkstra = Dijkstra$AdventOfCode.Dijkstra(AdjacencyList$AdventOfCode.Node.Tuple2.StringInt)(NodeMap);
  let graph = {
    contents: AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make()
  };
  beforeEach(() => {
    graph.contents = AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.make();
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "2",
      2
    ], 7);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "3",
      3
    ], 9);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "1",
      1
    ], [
      "6",
      6
    ], 14);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "2",
      2
    ], [
      "3",
      3
    ], 10);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "2",
      2
    ], [
      "4",
      4
    ], 15);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "3",
      3
    ], [
      "4",
      4
    ], 11);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "3",
      3
    ], [
      "6",
      6
    ], 2);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "4",
      4
    ], [
      "5",
      5
    ], 6);
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addDirectedEdge(graph.contents, [
      "5",
      5
    ], [
      "6",
      6
    ], 9);
  });
  Jest.testAll("calculates correct shortest distance", {
    hd: [
      [
        "1",
        1
      ],
      0
    ],
    tl: {
      hd: [
        [
          "2",
          2
        ],
        7
      ],
      tl: {
        hd: [
          [
            "3",
            3
          ],
          9
        ],
        tl: {
          hd: [
            [
              "4",
              4
            ],
            20
          ],
          tl: {
            hd: [
              [
                "5",
                5
              ],
              26
            ],
            tl: {
              hd: [
                [
                  "6",
                  6
                ],
                11
              ],
              tl: /* [] */0
            }
          }
        }
      }
    }
  }, param => {
    let match = Dijkstra.dijkstra(graph.contents, [
      "1",
      1
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(match[0], param[0])), param[1]);
  });
  Jest.test("handles unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "7",
      7
    ]);
    let match = Dijkstra.dijkstra(graph.contents, [
      "1",
      1
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(match[0], [
      "7",
      7
    ])), undefined);
  });
  Jest.test("returns correct path", () => {
    let path = Dijkstra.shortestPath(graph.contents, [
      "1",
      1
    ], [
      "5",
      5
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), [
      [
        "1",
        1
      ],
      [
        "3",
        3
      ],
      [
        "4",
        4
      ],
      [
        "5",
        5
      ]
    ]);
  });
  Jest.test("returns None for unreachable nodes", () => {
    AdjacencyList$AdventOfCode.Node.Tuple2.StringInt.addNode(graph.contents, [
      "7",
      7
    ]);
    let path = Dijkstra.shortestPath(graph.contents, [
      "1",
      1
    ], [
      "7",
      7
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(path), undefined);
  });
  let shortestPathsTestData_0 = [
    [
      "1",
      1
    ],
    [[
        "1",
        1
      ]]
  ];
  let shortestPathsTestData_1 = {
    hd: [
      [
        "2",
        2
      ],
      [
        [
          "1",
          1
        ],
        [
          "2",
          2
        ]
      ]
    ],
    tl: {
      hd: [
        [
          "3",
          3
        ],
        [
          [
            "1",
            1
          ],
          [
            "3",
            3
          ]
        ]
      ],
      tl: {
        hd: [
          [
            "4",
            4
          ],
          [
            [
              "1",
              1
            ],
            [
              "3",
              3
            ],
            [
              "4",
              4
            ]
          ]
        ],
        tl: {
          hd: [
            [
              "5",
              5
            ],
            [
              [
                "1",
                1
              ],
              [
                "3",
                3
              ],
              [
                "4",
                4
              ],
              [
                "5",
                5
              ]
            ]
          ],
          tl: {
            hd: [
              [
                "6",
                6
              ],
              [
                [
                  "1",
                  1
                ],
                [
                  "3",
                  3
                ],
                [
                  "6",
                  6
                ]
              ]
            ],
            tl: /* [] */0
          }
        }
      }
    }
  };
  let shortestPathsTestData = {
    hd: shortestPathsTestData_0,
    tl: shortestPathsTestData_1
  };
  Jest.testAll("returns correct paths for all nodes", shortestPathsTestData, param => {
    let paths = Dijkstra.shortestPaths(graph.contents, [
      "1",
      1
    ]);
    return Jest.Expect.toEqual(Jest.Expect.expect(NodeMap.get(paths, param[0])), param[1]);
  });
});

let StringAdjList;

let TupleAdjList;

export {
  StringAdjList,
  TupleAdjList,
}
/*  Not a pure module */
