// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2019_Day3 from "./AOC2019_Day3.res.mjs";
import * as AOC2019_Day3_Data from "./AOC2019_Day3_Data.res.mjs";
import * as AOC2019_Day3_Data_Sample from "./AOC2019_Day3_Data_Sample.res.mjs";

function log(prim) {
  console.log(prim);
}

console.time("Part 1");

let part1 = AOC2019_Day3.solvePart1(AOC2019_Day3_Data_Sample.data);

console.log("Part 1 Result");

console.log(part1);

console.timeEnd("Part 1");

console.log("----------");

let data = AOC2019_Day3_Data.data;

let sampleData = AOC2019_Day3_Data_Sample.data;

let sampleData1 = AOC2019_Day3_Data_Sample.data1;

let sampleData2 = AOC2019_Day3_Data_Sample.data2;

let solvePart1 = AOC2019_Day3.solvePart1;

let solvePart2 = AOC2019_Day3.solvePart2;

export {
  log,
  data,
  sampleData,
  sampleData1,
  sampleData2,
  solvePart1,
  solvePart2,
  part1,
}
/*  Not a pure module */
